### ISSUE TITLE
500 Errors with dynamic routes + getStaticProps

### ISSUE THREAD

**Issue by cassidoo** [FinnWoelm/next-on-netlify#14]
I'm so excited about v2 of this library! Unfortunately I ran into a couple issues with it when trying to query an API based on a dynamic route.

Here's what my code looked like before with `getStaticProps` and using the new incremental stuff:
https://github.com/cassidoo/sonnet-18/blob/c91e5468e5524b773537a89b73fbd7632ea735e4/pages/compare/%5B...slug%5D.js

And it works great when I change it to use `getInitialProps`:
https://github.com/cassidoo/sonnet-18/blob/master/pages/compare.js

The code is doing pretty much the exact same thing, except I pull it from a query string in the latter, and from the dynamic path in the first one. It worked fine locally on my machine, but on Netlify itself when I tried to navigate to the paths, it gave a 500 error.
I do prefer the query string way, but when talking with the Next.js team themselves, they recommended the other way with the paths, and I'd like to stick with the recommended way if I can.

I tried debugging a few times but this seems to the the only working solution for now. Happy to give more info if needed!

**Comment by FinnWoelm** [comment]
Hi @cassidoo,

It's great to hear from you! Thanks for checking out v2!

I actually read about you a few days ago, because I was looking at the top hits for "NextJS with Netlify" on Google and it's [your tutorial from May](https://www.netlify.com/blog/2020/05/04/building-a-markdown-blog-with-next-9.4-and-netlify/). Perhaps we can make one with `next-on-netlify`? :upside_down_face: 

I forked sonnet-18 to dig into the issue (neat repo, by the way :blush:). The issue is with the hash symbols in the URL used to join repository owner and repository name (`owner#repo`). Even though they are encoded as `%23` in the URL, they are decoded when they arrive in the Netlify Function. This makes NextJS only pass the path up to the first hash symbol to the page.

For example,
- if the path is `compare/cassidoo%23sonnet-18/finnwoelm%23sonnet-18`,
- the Netlify Function receives this as `/test/cassidoo#sonnet-18/finnwoelm#sonnet-18`.
- NextJS then sees the path as `/test/cassidoo`. Everything after the first hash is not part of the path.
- NextJS then sends `params: { slug: ["cassidoo"] }` to the page.
- Octokit then looks for a GitHub repo with `owner: "cassidoo"` and `repo: ""`, cannot find it and returns a 404
- In turn, this causes NextJS to throw a 500 error

I think this may be a bug with Netlify Functions — as you rightly pointed out, it works perfectly locally with `next dev` and `netlify dev`. There's a discrepancy between Netlify Functions locally and Netlify Functions on netlify.app. To illustrate this, I created [a `test.js` Netlify Function that prints out all params received](https://github.com/FinnWoelm/sonnet-18/blob/master/functions/test.js).

**Local with netlify dev:** http://localhost:8888/test/cassidoo%23sonnet-18/finnwoelm%23sonnet-18
```json
{
  "event": {
    "path": "/test/cassidoo%23sonnet-18/finnwoelm%23sonnet-18",
    "httpMethod": "GET",
    "queryStringParameters": {},
    "headers": {
      "x-forwarded-for": "::ffff:127.0.0.1",
      "upgrade-insecure-requests": "1",
      "connection": "close",
      "dnt": "1",
      "accept-encoding": "gzip, deflate",
      "accept-language": "en-US,en;q=0.5",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
      "host": "localhost:8888",
      "client-ip": "127.0.0.1"
    },
    "isBase64Encoded": false
  },
  "context": {
    "callbackWaitsForEmptyEventLoop": false,
    "functionName": "handler",
    "functionVersion": "1.0",
    "invokedFunctionArn": "arn:aws:lambda:us-east-1:72269096276:function:handler:1.0",
    "memoryLimitInMB": 519,
    "awsRequestId": "4f3560a2-ccb8-d7e6-a794-40586cc6aeee",
    "logGroupName": "Group name",
    "logStreamName": "Stream name",
    "identity": null,
    "clientContext": {},
    "_stopped": false
  }
}
```

**Production:** https://cassidoo-sonnet-18.netlify.app/test/cassidoo%23sonnet-18/finnwoelm%23sonnet-18
```json
{
  "event": {
    "path": "/test/cassidoo#sonnet-18/finnwoelm#sonnet-18",
    "httpMethod": "GET",
    "headers": {
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "accept-encoding": "br, gzip",
      "accept-language": "en-US,en;q=0.5",
      "client-ip": "37.165.195.216",
      "dnt": "1",
      "upgrade-insecure-requests": "1",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
      "via": "https/2 Netlify[9605f1ef-ac01-4ee8-9b38-1aba2e1495fa] (ApacheTrafficServer/7.1.10)",
      "x-bb-ab": "0.964746",
      "x-bb-client-request-uuid": "9605f1ef-ac01-4ee8-9b38-1aba2e1495fa-4216664",
      "x-bb-ip": "37.165.195.216",
      "x-bb-loop": "1",
      "x-country": "FR",
      "x-forwarded-for": "37.165.195.216",
      "x-forwarded-proto": "https",
      "x-language": "en,en;q=0.5",
      "x-nf-client-connection-ip": "37.165.195.216"
    },
    "multiValueHeaders": {
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
      ],
      "Accept-Encoding": [
        "br, gzip"
      ],
      "Accept-Language": [
        "en-US,en;q=0.5"
      ],
      "Client-Ip": [
        "37.165.195.216"
      ],
      "Dnt": [
        "1"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "User-Agent": [
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
      ],
      "Via": [
        "https/2 Netlify[9605f1ef-ac01-4ee8-9b38-1aba2e1495fa] (ApacheTrafficServer/7.1.10)"
      ],
      "X-Bb-Ab": [
        "0.964746"
      ],
      "X-Bb-Client-Request-Uuid": [
        "9605f1ef-ac01-4ee8-9b38-1aba2e1495fa-4216664"
      ],
      "X-Bb-Ip": [
        "37.165.195.216"
      ],
      "X-Bb-Loop": [
        "1"
      ],
      "X-Country": [
        "FR"
      ],
      "X-Forwarded-For": [
        "37.165.195.216"
      ],
      "X-Forwarded-Proto": [
        "https"
      ],
      "X-Language": [
        "en,en;q=0.5"
      ],
      "X-Nf-Client-Connection-Ip": [
        "37.165.195.216"
      ]
    },
    "queryStringParameters": {},
    "multiValueQueryStringParameters": {},
    "body": "",
    "isBase64Encoded": true
  },
  "context": {
    "callbackWaitsForEmptyEventLoop": true,
    "functionVersion": "$LATEST",
    "functionName": "536a0610ec0a2e21a9dc49c87915497f3d43c413de7520609cd2d48355aa4189",
    "memoryLimitInMB": "1024",
    "logGroupName": "/aws/lambda/536a0610ec0a2e21a9dc49c87915497f3d43c413de7520609cd2d48355aa4189",
    "logStreamName": "2020/06/06/[$LATEST]4e02a7a5f21e452b814c229d77eb3761",
    "clientContext": {
      "custom": {
        "netlify": "eyJzaXRlX3VybCI6Imh0dHBzOi8vY2Fzc2lkb28tc29ubmV0LTE4Lm5ldGxpZnkuYXBwIn0="
      }
    },
    "invokedFunctionArn": "arn:aws:lambda:us-east-1:073635757191:function:536a0610ec0a2e21a9dc49c87915497f3d43c413de7520609cd2d48355aa4189",
    "awsRequestId": "a1ecdff1-90f0-4d85-ba92-df1510aaa815"
  }
}
```

Note that the very first parameter `event.path` differs between a deployed Netlify Function and a locally-run Netlify Function. Specifically, you will see that the hash symbols are no longer encoded in the deployed Netlify Function. I'm not sure if this is a bug or a feature... Perhaps you know some folks who could look into it :grin: 

Until this is fixed, it's probably better to use a different symbol. For example, here is a version using colons rather than hashes: https://cassidoo-sonnet-18.netlify.app/compare/cassidoo:sonnet-18/FinnWoelm:sonnet-18
Repo: https://github.com/FinnWoelm/sonnet-18

Let me know what you think and whether this fixes the issue! Happy to dig some more, if it would be helpful.
\- Finn

PS: I saw your issue regarding the `next-on-netlify` demo page. Thanks for catching that! Will look into very soon.

**Comment by cassidoo** [comment]
This makes sense!! I had to use the symbol because of a Next.js bug, so... bugs all around 😆 

I do want to write some blog posts with this package, I think it's awesome. I'll try the colon thing and see how that works!

**Comment by cassidoo** [comment]
@FinnWoelm, thanks so much for looking into this, it was all super useful! I redeployed everything, so now I have both the `getInitialProps` way and the `getStaticProps` way built:

https://sonnet-18.netlify.app/
https://sonnet-18-incremental.netlify.app/

Also, I do think that you were right about it being a minor bug in Netlify Functions, and I've told the team about it to try and get it fixed. Closing this issue now, thank you again! Let's talk soon and get some more blog posts out using this package :)

**Comment by cassidoo** [comment]
@FinnWoelm update here. I noticed both in yours (and my) projects, when you use a repo that hasn't been compared before, you get a 500 error, and then you refresh and it works just fine. I can just output "null" and make the page say "please refresh!", but it kind of is a crappy experience for the whole incremental static regen thing. Any ideas?

**Comment by FinnWoelm** [comment]
Hey @cassidoo,

Thank you for [the awesome `next-on-netlify` tutorial on Netlify.com](https://www.netlify.com/blog/2020/06/10/2-ways-to-create-server-rendered-routes-using-next.js-and-netlify/)! I've noticed an influx of new people taking a look and testing out `next-on-netlify` :slightly_smiling_face: 

Did you get a chance to take another look at the error 500 issue? As far as I can tell, it's really related to the response from the GitHub API rather than to `next-to-netlify` in any way.

Cheers :blush:
