### ISSUE TITLE
Unmatched paths return Netlify page

### ISSUE THREAD

**Issue by ericchernuka** [FinnWoelm/next-on-netlify#16]
First off, love this project.

I have an issue, but I'm not sure if its this project's responsibility or next in general. In my project, I have a single route that's a fully dynamic route `/[businessUnit]/[pageSlug]/[hash]` and locally if you hit `/`, `/sales`, `/sales/qs` it returns the error page, but once deployed it shows the Netlify no route found message instead of the error page. Any thoughts on how this should be approached with `next-on-netlify`?

**Comment by FinnWoelm** [comment]
Hey @ericchernuka,

Thanks for the kind words about `next-on-netlify` :blush: 

Hmm, interesting...

The `_redirects` file not having a redirect for `404.html` is normal and fine. Netlify automatically looks for a `404.html` in the publish folder and makes that the default 404 for the page.

Do you have a repo I can clone? Or could you set up a very basic one where I can reproduce the error? That would be really helpful.

I'll look into this tonight! :slightly_smiling_face:  
\- Finn

**Comment by ericchernuka** [comment]
@FinnWoelm Thanks for looking into this. I've made a sample repo here: https://github.com/ericchernuka/next-on-netlify-error-pages

I wonder if its cause I have a 404.tsx, but it gets compiled as a serverless function instead of 404.html.

**Comment by FinnWoelm** [comment]
Hey @ericchernuka,

Thank you for setting up a repo! That was incredibly helpful.

Your suspicion is right: The issue is that the 404.tsx file gets compiled as a serverless function rather than a 404.html.

You probably know this already: You can see what NextJS builds by running `npm run build` locally and looking at the `.next` folder:

![image](https://user-images.githubusercontent.com/7606194/84547711-5ffb4a80-ad04-11ea-901d-0fcd8ebb1853.png)

Normally, the 404.js/404.tsx file gets compiled as a static 404.html file. But by adding `getInitialProps` in `_app.js`, **all** files get compiled as serverless functions rather than plain HTML files — including the 404 page.

Two options:
1. You move the `getInitialProps` from `_app.tsx` to `[repoName].tsx`. You can still use the custom `render` function to wrap your page in `border-red-500`. And you can keep the `if(error) return <FourOhFour />`, too. You'll just need to shift the responsibility for setting `error: true` from `_app.tsx` to `[repoName].tsx`.
2. You keep your code as is, meaning that the 404 page (and all other pages) are serverless functions. In that case, just add a catch-all redirect, similar to the one you have above. You just need to redirect to the Netlify Function rather than to `/404`. The redirect should be:
```
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_404"
  status = 404
```

You can find out what the redirect destination should be from the build output of `next-on-netlify`:
```
...
🔀 Setting up redirects
   /404  /.netlify/functions/next_404  200
   /:org/:repoName  /.netlify/functions/next_org_repoName  200
   /_next/data/He6qRDFHlbXa4vp6B8igE/:org/:repoName.json  /.netlify/functions/next_org_repoName  200
...
```

The first one is the relevant line!

Does that make sense? Does that help? Let me know what you think! Curious to hear your thoughts on this.

Happy Friday,
Finn

**Comment by ericchernuka** [comment]
This is immensely helpful. Thank you. Due to the way my project works I need the getInitialProps in _app to fetch an overall theme first so I'll most likely move towards a catchall redirect for this use case. Thanks again looking into this for me.

**Comment by pgr86** [comment]
Hi Finn, 
I have a similar issue and followed your instructions with option number two. I added the mentioned code to the netlify.toml file. Now it renders my custom 404 page, instead the netlify not-found page. But the response status code is still 200. I made several tests - seems to me that it is not possible to change the response of a netlify function within the _redirects or netlify.toml file - e.g. status code or even headers like cache-control.

Did I missed anything?

**Comment by FinnWoelm** [comment]
Hi @pgr86, interesting! You are right, setting the status to 404 via the netlify.toml file does not work for Netlify Functions.

### Fix 1: Manually set 404 in getInitialProps in _app.js

I would have expected the Next 404 page to take care of setting the 404 status code. I think this is a bug in NextJS. Anyway, we can fix this ourselves by manually setting the 404 status in `getInitialProps` in `_app.js` like this :

```javascript
// pages/_app.js

...

export default class MyApp extends NextApp<MyAppProps> {
  static async getInitialProps(appContext: AppContext) {

    // Manually set status 404 if rendering 404 not found page
    if(appContext?.ctx?.res && appContext?.ctx?.pathname === "/404") {
      appContext.ctx.res.statusCode = 404
    }

    // more code, like:
    // const appProps = await NextApp.getInitialProps(appContext);
    // etc ...

  }
}

...

```

----

### Fix 2: Pre-render your 404 page to HTML

The solution above is not really not ideal because all 404 requests now invoke a Netlify function — when a route cannot be found, but also for any other unmatched requests (such as missing favicons or other assets). Ideally, of course, you can refactor your code to not use `getInitialProps` in `_app.js`. But that's not always possible. Another option is to manually pre-render your 404 page to HTML. You can do that using something like the following script:

```javascript
// scripts/404ToHtml.js

const compat  = require("next-aws-lambda")
const page    = require("./out_functions/next_404/nextJsPage")
const fs      = require('fs')

// These two objects usually contain the HTTP request information and
// data about the environment in which the Netlify Function is invoked (AWS
// server ID, etc...). In this case, they don't matter and can just be empty.
const event = { requestContext: {} }
const context = {}

// This is our render callback handler. It writes the response body to 404.html
// in out_publish/
const writePageHtml = (_arg, response) => {
  fs.writeFileSync('./out_publish/404.html', response.body)
}

// Render the page
compat(page)(
  event,
  context,
  writePageHtml
)
```

The script is similar to the code of the Netlify Functions created by this package (see https://github.com/netlify/next-on-netlify/blob/master/lib/netlifyFunctionTemplate.js). We take advantage of the fact that the serverless NextJS pages are just JavaScript functions that we can invoke and get the HTML back. We then take that HTML and write the 404.html to out_publish/.

We can just add this script to our postbuild process in `package.json`, for example:

```
"postbuild": "next-on-netlify && node scripts/404ToHtml.js"
```

In this case, we of course do not need the catch-all redirect in `netlify.toml` and Netlify will automatically set status code 404!

---- 

I hope one of the solutions above works for you. Please let me know if it does :slightly_smiling_face: If not, don't hesitate let me know if you run into any issues. Happy to continue looking into this!

**Comment by pgr86** [comment]
Hi @FinnWoelm 
wow thank you so much for that detailed answer! I went the pre-render way and it works really well :-) 
This approach is also very helpful for me to better understand how next-on-netlify works under the hood.

Thanks so much for your great work on this package!
