### ISSUE TITLE
How to create a function on Netlify using this v2?

### ISSUE THREAD

**Issue by Djepri** [FinnWoelm/next-on-netlify#19]
Hi,

I try to access this function 
https://sonnet-18.netlify.app/.netlify/functions/github
but got 404
instead, the function created on Netlify is 
https://sonnet-18.netlify.app/.netlify/functions/next_compare?repos=FinnWoelm%23next-on-netlify,cassidoo%23sonnet-18

Is this because of next-on-netlify v2 or multiValueHeaders change?

**Comment by FinnWoelm** [comment]
Hi @Djepri,

Great to hear from you!

I believe you are referring to https://github.com/cassidoo/sonnet-18? The github.js function (https://github.com/cassidoo/sonnet-18/blob/master/functions/github.js) and the next_compare.js function are actually not related.

`next-on-netlify` v2 now creates one Netlify Function for every page that requires server-side rendering (any page that uses either `getStaticProps` with fallback: true, `getServerSideProps`, or `getInitialProps`). Each page now gets its own Netlify Function. So the next_compare function is created for server-side rendering the `pages/compare.js` page: https://github.com/cassidoo/sonnet-18/blob/master/pages/compare.js. This keeps the functions small and makes it easier to look through the function logs in the Netlify web interface.

The functions are written to `out_functions` and this is what should be in the `netlify.toml` file. Previously it was `functions`. See the README or let me know if there's anything you're unsure about.

`next-on-netlify` 2 completely ignores the `functions` folder. If you want to define API endpoints, the best way is to follow the NextJS aproach and place them in `pages/api`. That way, `next-on-netlify` automatically converts them into Netlify Functions. You can read about that here: https://nextjs.org/docs/api-routes/introduction

If you want a plain Netlify Function, you can copy it into the `out_functions` folder yourself. You should do this after running `next-on-netlify`, because `next-on-netlify` completely empties the folder every time it runs. For example, you could set up your `package.json` file like this:
```
  "scripts": {
    "build": "next build && next-on-netlify && cp functions/myFunction.js out_functions/myFunction.js"
  }
```

Does that help? Let me know if anything is unclear. Super happy to help!
\- Finn

**Comment by alxhghs** [comment]
I originally had a custom Netlify function but I didn't know about the pages/api feature, I like that a lot! Might not be bad to add a note about this in the readme, it's a very good solution to the problem.

**Comment by Djepri** [comment]
That helps me a lot
Thank you very much

**Comment by FinnWoelm** [comment]
Hey @Djepri, glad it helped! Do let me know if you run into any other issues at any point.

@alxhghs: Yes! I've really been wanting to update the demo repo and showcase the API feature there... will do soon!
