### ISSUE TITLE
Client-side navigation, react-hook-form and getInitialProps

### ISSUE THREAD

**Issue by alxhghs** [FinnWoelm/next-on-netlify#23]
Hello,

I've been trying to figure this issue out for the last 7 hours or so, so I decided to finally post an issue.

Next-on-netlify has worked great for my site. I use it with Storyblok CMS. Recently with Netlify updates and the new next-on-netlify v2 there are some breaking changes which I have narrowed down to `getInitialProps`.

I have a Page (`Index.tsx`) that I export and use on other dynamic routes. If I have `getInitialProps` on the `Index.tsx` page, client-side routing with `next/link` and `next/router` doesn't work. 

I could live without client-side routing but the bigger issue is that I use react-hook-form and the form submission is broken. Rather than handling submission it is posting form values to the URL like a GET request. 

Please let me know if I can share more information. I have worked a long time to figure out the issue and I finally narrowed it down to whether or not I use `getInitialProps`. `getStaticProps` and `getServerSideProps` don't seem to have the issue but I'm not sure if they are good replacements. Currently I am using `query`, `req` and `asPath` in `getInitialProps` and it didn't seem like those values were all available in either `getStaticProps` or `getServerSideProps`. 

Thanks for any help or suggestions!

**Comment by FinnWoelm** [comment]
Hey @alxhghs, great to see you again!

First of all, thanks for already diving into your code and narrowing down the problem! That is super helpful and absolutely appreciated!!

It sounds like there may be multiple issues coming together here. Client-side routing with `getInitialProps` should definitely work! As for `react-hook-form`, I have not used it myself, but that should work, too.

Is your site publicly on GitHub, so that I can take a look? Otherwise, can you put together a small example repo for reproducing the issue? More than happy to take a look asap! :blush: 

\- Finn

PS: As for accessing `query`, `req`, and `asPath`: For `getServerSideProps`, at least `req` is available. I believe `params` should be equivalent to `query`. For `asPath`, you may be able to get the URL or path from the `req` object. `getStaticProps` does not have `req` and `asPath` because it's usually pre-rendered and there is no HTTP request available at render-time. But I hope we can figure out how to make it work with `getInitialProps` rather than hacking together a workaround :upside_down_face:

**Comment by alxhghs** [comment]
Thanks for getting back to me! Unfortunately this site is a private repo but I did make an example repo. However, I tried to reproduce the issue and I wasn’t successful. There must be something else contributing to the issue that I haven’t been able to identify yet. 

Interestingly I deployed the project using Vercel’s hosting service and both client side routing and react hook form work correctly now. I’m really stumped as to why getInitialProps is causing issues for this site on Netlify. I may look into this further when I have time to see if there are any other packages that are causing issues.

**Comment by FinnWoelm** [comment]
Hmmmmm, that's really bizarre! Well, I'm super curious what's going on there. So if you do ever find time to look into this again, I'd be more than happy to help and bug-hunt with you!

Until then, happy hacking :fire: :slightly_smiling_face:
