### ISSUE TITLE
Custom Redirects Not Showing Up In Production Build _redirects File

### ISSUE THREAD

**Issue by jordan-mcrae** [FinnWoelm/next-on-netlify#27]
Hi there! 

Thank you so much for this awesome utility. We have been loving it so far!

We're running into an issue where our custom redirects are showing up in our local build, but when deploying to Netlify, all we see are the `# Next-on-Netlify Redirects`.

Here's our netlify.toml file:

```
[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[dev]
  functions = "functions"
  publish   = "public"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects NextJS and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"
```

Here's our _redirect file in the root of our project that should redirect /test to our home page:

```
/test/ /
```

Here are our scripts in our package.json:

```
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "postbuild": "next-on-netlify"
  },
```

The custom redirect does not get added to the `out_publish/_redirects` file on Netlify, but if we create build locally, it does.

We've even tried re-deploying with cache clear and no luck.
![image](https://user-images.githubusercontent.com/30672643/88950431-a1b76480-d262-11ea-9618-04c866bd4ddc.png)

Do you have any ideas of what might be happening here? We also tried adding this redirect to our netlify.toml file, and still had no luck.

Thank you!

**Comment by FinnWoelm** [comment]
Hi @jordan-mcrae,

Thank you for the kind words! Happy that you like `next-on-netlify` :blush: 

That is indeed strange! I just tried to reproduce the issue with a super minimal build, but without success.

Here is the repo: https://github.com/FinnWoelm/jordan-mcrae-next-on-netlify
Here is the the /test/ link that redirects: https://jordan-mcrae-next-on.netlify.app/test

Your project is not open source, is it? I'm asking because it's always easier to be able to see what your set up is like.

Otherwise, a couple questions:

- Do you have version 2.3.1 of `next-on-netlify` in your `package-lock.json`?
- Does the build process on netlify.com say `# Prepending custom redirects` or not? This tells you whether next-on-netlify found your `_redirects` file at the root level. 

```
7:59:24 AM: 🔀 Setting up redirects
7:59:24 AM:    # Prepending custom redirects
7:59:24 AM:    /  /index.html  200
7:59:24 AM:    /404  /404.html  200
```

- Do you have a special folder structure (e.g., you have a mono-repo and you deploy a subfolder to Netlify?) or does your folder structure more or less match the one in the example repo: https://github.com/FinnWoelm/jordan-mcrae-next-on-netlify
- When you download the Netlify deploy, the `out_publish/_redirects` file does **not** have your custom redirects? Did I understand that correctly?

![download-deploy](https://user-images.githubusercontent.com/7606194/89005524-f90e1100-d304-11ea-9509-2fe0feb7b54d.png)


If none of the above help, do you think you can reproduce the issue in a repo? I would love to get to the bottom of this.

Another option would be to patch the next-on-netlify code and debug what's going on. Are you familiar with https://www.npmjs.com/package/patch-package? You can go make changes in `/node_modules/next-on-netlify/` For example, you might want to add a `console.log(CUSTOM_REDIRECTS_PATH)` line in https://github.com/FinnWoelm/next-on-netlify/blob/54ab91bd9b61c2b92c852150fa021674e2c69b4c/lib/setupRedirects.js#L34-L37

and check if the patch matches the location of the `_redirects` file.

But this can be a bit tricky, so I'm also super happy to debug if we can somehow reproduce the problem. Let's figure this out :grin:

**Comment by jordan-mcrae** [comment]
@FinnWoelm Thank you so much for the elaborate response and for looking into this so thoroughly for me. Frustratingly,  package.lock ended up being the culprit. I was stuck at 2.0.0. I sincerely appreciate the help, and if there's any way I can buy you a coffee let me know!

**Comment by FinnWoelm** [comment]
@jordan-mcrae hehe I know exactly what that feels like, because I've done that more times than I would like to admit :sweat_smile:  I'm really glad to hear that you were able to get to the bottom of it!

Thank you for the coffee offer. Much appreciated :raised_hands: There's no good way to do that at the moment, so perhaps you can just pay it forward :blush:

Let me know if you build [something awesome that we can feature in the README](https://github.com/FinnWoelm/next-on-netlify#showcase) :fire: Until then, happy hacking!
