### ISSUE TITLE
API route not passing query string

### ISSUE THREAD

**Issue by wei** [FinnWoelm/next-on-netlify#9]
API route is not passing query string.

Repo:
https://github.com/wei/next-on-netlify-demo-wei

Example:
https://relaxed-mirzakhani-568b34.netlify.app/api/debug/12345?testqs=1

```javascript
// api/debug/[id].js
export default async ( req, res ) => {
    res.json({ query: req.query });
    res.end();
};
```

Expected output
```
// npm run dev
{
    "query": {
        "testqs": "1",
        "id": "12345"
    }
}
```

Actual output
```
// npm run netlfy:dev
{
    "query": {
        "id": "12345"
    }
}
```

**Comment by FinnWoelm** [comment]
Hey @wei, great to hear from you again :)

Thanks for catching this issue! I'm working on a solution right now :slightly_smiling_face: 

I'll get back to you very soon!

**Comment by FinnWoelm** [comment]
Okay, I have some good news: The fix for this is relatively small!

Example: https://vigilant-lalande-4e2572.netlify.app/api/debug/12345?testqs=1&works=true
Code: https://github.com/FinnWoelm/next-on-netlify-demo-wei

Because it changes how things work, I would like to hold this commit back until the release of the upcoming next-on-netlify v2. I need to do a bit more work on a few things, so it may be another week or two until v2 comes out.

If you want to have query params right now, you can use the `support-query-params` branch:
```
npm install --save FinnWoelm/next-on-netlify#support-query-params
```
It has support for query params, but it's not a long-term branch. When I publish v2 of next-on-netlify, I'll notify you here and then delete that branch about ~30 days after. How does that sound?

Let's also keep this issue open for now :slightly_smiling_face:

**Comment by wei** [comment]
Thanks for the help!! Sounds great,I'll check it out. 😁

**Comment by FinnWoelm** [comment]
Hey @wei,

Quick status update: I'm still working on next-on-netlify v2. Support for query string parameters is now fully implemented. And I finally got around to writing tests with Jest and e2e tests with Cypress.

You may have noticed that the API endpoint you shared did not have the correct JSON content-type. This was due to `multiValueHeaders` which are not supported by Netlify. I filed an issue today: https://github.com/netlify/cli/issues/923 

In the meantime, I've implemented a work-around for setting the correct headers (and any custom headers, too) by converting `multiValueHeaders` into plain `headers`. This will go live with the release of v2.

I would like tackle issues #2 and #7 before releasing v2, so please bear with me for a bit longer :grin: 


Hope you're doing well!
Finn

**Comment by wei** [comment]
Thanks for keeping me posted! btw it looks like there is an extranuous
```
const multiValueHeaders = 
```
in the snippet from the issue you opened on netlify/cli.

**Comment by FinnWoelm** [comment]
Oops, great catch! Thanks! Fixed that :heavy_check_mark:

**Comment by laugharn** [comment]
Thanks for the work you're doing on this!

**Comment by FinnWoelm** [comment]
Hey @wei,

`next-on-netlify` v2 is finally out :tada: :tada: You can see the [full list of changes in the changelog](https://github.com/FinnWoelm/next-on-netlify/blob/master/CHANGELOG.md#200-2020-06-02). 

Thank you for your bug-hunting (and for catching my typos :grin:)!

You'll need to make some changes to your `netlify.toml` for v2, both for deployment and for local preview:

```toml
# netlify.toml

[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  framework = "#static"
```

And you will want to adjust your `.gitignore`:
```bash
# .gitignore

# Files generated by next-on-netlify command
/out_publish/
/out_functions/
/404.html
```

Let me know if you run into any trouble. I closed this issue for now, but let's reopen it at any time if necessary! And if you build something awesome, let me know, too! I'd love to feature some real-world projects in the README.

Happy hacking! :fire: 
Finn
